{% set name = "palantir-oauth-client" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/palantir-oauth-client-{{ version }}.tar.gz
  sha256: 113241cb334bc19b2b5c17ad0a350ed32ba766d74155b1d074e68351e485538b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=35.0.2
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - oauthlib >=3.2.2
    - requests >=2.28.2
    - requests-oauthlib >=1.3.1
    - urllib3 >=1.26.14

test:
  requires:
    - python {{ python_min }}
  imports:
    - palantir_oauth_client

about:
  home: https://github.com/palantir/palantir-oauth-client
  summary: OAuth2 client for Palantir Foundry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ahggns
    - tom-s-powell
    - AlexandreGuinaudeau
    - talDias
